# Supported funding model platforms

tidelift: packagist/filips123/monolog-phpmailer

github: filips123
patreon: filips
ko_fi: filips
liberapay: filips
custom: ['https://donorbox.org/filips', 'https://buymeacoff.ee/filips']
