language: php
dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update --no-interaction --no-progress --no-suggest --prefer-dist
  - mkdir -p build/cov

script:
  # Test with Monolog 1.x
  - travis_retry composer require monolog/monolog:^1.0
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-php ./build/cov/monolog1.cov

  # Test with Monolog 2.x
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" && ${TRAVIS_PHP_VERSION:2:1} != "0" ]]
    then
      travis_retry composer require monolog/monolog:^2.0@dev
      vendor/bin/phpcs
      vendor/bin/phpunit --coverage-php ./build/cov/monolog2.cov
    fi

after_script:
  # Merge coverage reports for tests with Monolog 1.x and 2.x
  - vendor/bin/phpcov merge --clover ./build/clover.xml ./build/cov

  # Upload coverage report when running PHP 7.2
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]
    then
      travis_retry wget --no-verbose https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
    fi
